services:
  webapplication4:
    image: ${DOCKER_REGISTRY-}webapplication4
    build:
      context: .
      dockerfile: WebApplication4/Dockerfile
      target: final
    environment:
      - USER_SECRETS_ID=a933e274-f1d6-45d6-8484-fd398900449e
      - CONN_STRING=User ID=postgres;Password=postgres;Host=database;Port=5432;Database=postgres;Pooling=true;
  database:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      volumes:
        - ./DbSchemas:/docker-entrypoint-initdb.d
  rabbitmq:
      image: rabbitmq:4-management
      container_name: rabbitmq
      ports:
      - "5672:5672"
      - "15672:15672"