# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # lub nowsza, jeśli projekt używa 6/7

    - name: Restore dependencies
      run: dotnet restore WebApplication4.sln

    - name: Build
      run: dotnet build WebApplication4.sln --no-restore

    - name: Test
      run: dotnet test WebApplication4.sln --no-build --verbosity normal
