name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        persist-credentials: true

    - name: Initialize submodules explicitly (optional)
      run: git submodule update --init --recursive

    - name: Show directory structure
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore WebApplication4.sln

    - name: Build
      run: dotnet build WebApplication4.sln --no-restore

    - name: Test
      run: dotnet test WebApplication4.sln --no-build --verbosity normal
